
_NOT_ENROLLED = 0
_ENROLLED_ONLINE = 1
_ENROLL_CONFIRMED = 2
_ENROLL_DISCONTINUED = (3, 4)  # 3 - DISCONTINUED, 4 - DROPPED OUT
_ENROLL_PROMOTED = 5
_WAIT_LISTED = 6

_SYMBOL_TICK = '✅'
_SYMBOL_UNTICK = '❌'
_SYMBOL_LOCK = '⛔'

_EVENT_ID = None
_NOT_PARTICIPATING_PROGRAM_NAME = "Not Participating"
